repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--diff]
      language_version: python3
    - id: black
      name: black-format
      language_version: python3
      stages: [manual]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    - id: flake8
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      args: [-E, -j4, --disable=invalid-sequence-index, --disable=no-member, --disable=no-name-in-module]
      language: system
      types: [python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.670'
    hooks:
    -   id: mypy
